package users

import (
	"context"
	"database/sql"
	"errors"

	"github.com/waqasmani/go-auth-boilerplate/internal/db"
	apperrors "github.com/waqasmani/go-auth-boilerplate/internal/errors"
)

//go:generate mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks

// Repository defines data-access for the users module.
type Repository interface {
	GetUserByID(ctx context.Context, id string) (*db.User, error)
	GetUserByIDWithRoles(ctx context.Context, id string) (*UserResponse, error)
}

type repository struct {
	queries *db.Queries
}

// NewRepository constructs a users repository.
func NewRepository(queries *db.Queries) Repository {
	return &repository{queries: queries}
}

func (r *repository) GetUserByID(ctx context.Context, id string) (*db.User, error) {
	user, err := r.queries.GetUserByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, apperrors.ErrNotFound
		}
		return nil, apperrors.Wrap(apperrors.ErrInternalServer, err)
	}
	return &user, nil
}

// GetUserByIDWithRoles runs the LEFT JOIN query generated by sqlc and assembles
// the result into a UserResponse with the roles slice populated.
// Returns ErrNotFound when no rows are returned (user does not exist).
func (r *repository) GetUserByIDWithRoles(ctx context.Context, id string) (*UserResponse, error) {
	rows, err := r.queries.GetUserByIDWithRoles(ctx, id)
	if err != nil {
		return nil, apperrors.Wrap(apperrors.ErrInternalServer, err)
	}
	if len(rows) == 0 {
		return nil, apperrors.ErrNotFound
	}

	resp := &UserResponse{
		ID:        rows[0].ID,
		Name:      rows[0].Name,
		Email:     rows[0].Email,
		Roles:     []string{},
		CreatedAt: rows[0].CreatedAt,
		UpdatedAt: rows[0].UpdatedAt,
	}
	for _, row := range rows {
		if row.RoleName.Valid {
			resp.Roles = append(resp.Roles, row.RoleName.String)
		}
	}
	return resp, nil
}
