version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - unused
    - gocritic
    - bodyclose
    - misspell

formatters:
  enable:
    - gofmt
    - goimports
