// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_email.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const clearEmailVerified = `-- name: ClearEmailVerified :exec
UPDATE users
SET
    email_verified_at = NULL,
    updated_at        = NOW()
WHERE
    id = ?
`

// Clears email_verified_at after a password reset so the account must
// re-confirm inbox ownership before logging in again. This closes the
// window where an attacker who hijacked the victim's inbox resets the
// password and immediately inherits a verified, session-capable account.
// Idempotent: safe to call when the column is already NULL.
func (q *Queries) ClearEmailVerified(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.clearEmailVerifiedStmt, clearEmailVerified, id)
	return err
}

const consumeEmailToken = `-- name: ConsumeEmailToken :execresult
UPDATE email_tokens
SET
    used_at = NOW()
WHERE
    id = ?
    AND used_at IS NULL
`

// Atomically marks a token as used. The WHERE guard ensures exactly
// one concurrent caller gets RowsAffected = 1; any racing caller gets
// 0, which the service treats as a replay attempt.
func (q *Queries) ConsumeEmailToken(ctx context.Context, id string) (sql.Result, error) {
	return q.exec(ctx, q.consumeEmailTokenStmt, consumeEmailToken, id)
}

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO
    email_tokens (id, user_id, token_hash, token_type, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, NOW())
`

type CreateEmailTokenParams struct {
	ID        string               `json:"id"`
	UserID    string               `json:"user_id"`
	TokenHash string               `json:"token_hash"`
	TokenType EmailTokensTokenType `json:"token_type"`
	ExpiresAt time.Time            `json:"expires_at"`
}

// Inserts a new email token record. The raw token is never stored;
// only the SHA-256 hex hash (CHAR(64)) is persisted, matching the
// same pattern as refresh_tokens.
func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.exec(ctx, q.createEmailTokenStmt, createEmailToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.TokenType,
		arg.ExpiresAt,
	)
	return err
}

const getEmailTokenByHash = `-- name: GetEmailTokenByHash :one
SELECT
    id,
    user_id,
    token_hash,
    token_type,
    used_at,
    expires_at,
    created_at
FROM email_tokens
WHERE
    token_hash = ?
LIMIT 1
`

// Retrieves the full token record by its SHA-256 hex hash so the
// service layer can inspect used_at / expires_at before consuming it.
// No WHERE used_at IS NULL filter — the service layer decides which
// state transitions are valid for each token_type.
func (q *Queries) GetEmailTokenByHash(ctx context.Context, tokenHash string) (EmailToken, error) {
	row := q.queryRow(ctx, q.getEmailTokenByHashStmt, getEmailTokenByHash, tokenHash)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenType,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserTokensByType = `-- name: InvalidateUserTokensByType :exec
UPDATE email_tokens
SET
    used_at = NOW()
WHERE
    user_id = ?
    AND token_type = ?
    AND used_at IS NULL
`

type InvalidateUserTokensByTypeParams struct {
	UserID    string               `json:"user_id"`
	TokenType EmailTokensTokenType `json:"token_type"`
}

// Soft-deletes (marks used) all live tokens of a given type for a
// user before issuing a new one. Prevents a user from holding multiple
// valid reset/verify tokens simultaneously.
func (q *Queries) InvalidateUserTokensByType(ctx context.Context, arg InvalidateUserTokensByTypeParams) error {
	_, err := q.exec(ctx, q.invalidateUserTokensByTypeStmt, invalidateUserTokensByType, arg.UserID, arg.TokenType)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET
    email_verified_at = NOW(),
    updated_at        = NOW()
WHERE
    id = ?
`

// Stamps email_verified_at once the user clicks the verification link.
// Idempotent: calling it on an already-verified user is a safe no-op
// (the column will simply be updated to NOW() again).
func (q *Queries) MarkEmailVerified(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.markEmailVerifiedStmt, markEmailVerified, id)
	return err
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens
SET    revoked_at = NOW()
WHERE  user_id    = ?
  AND  revoked_at IS NULL
`

// Called after a successful password reset to invalidate every active
// session for the user. Any attacker holding a stolen refresh token
// will get ErrTokenRevoked on their next /refresh call.
func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID string) error {
	_, err := q.exec(ctx, q.revokeUserRefreshTokensStmt, revokeUserRefreshTokens, userID)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET
    password_hash = ?,
    updated_at    = NOW()
WHERE
    id = ?
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string `json:"password_hash"`
	ID           string `json:"id"`
}

// Replaces the bcrypt hash after a successful password reset.
// updated_at is refreshed so cache-busting strategies based on that
// column work correctly.
func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.exec(ctx, q.updateUserPasswordHashStmt, updateUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}
