// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_users_tokens.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const assignUserRoleByName = `-- name: AssignUserRoleByName :execresult
INSERT INTO
    user_roles (user_id, role_id)
SELECT ?, r.id
FROM roles r
WHERE
    r.name = ?
LIMIT 1
`

type AssignUserRoleByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

// Assigns a role to a user by role name rather than by hard-coded role_id.
// The LIMIT 1 is defensive — role names are UNIQUE but this makes the intent
// explicit and prevents a runaway insert if that constraint were ever dropped.
func (q *Queries) AssignUserRoleByName(ctx context.Context, arg AssignUserRoleByNameParams) (sql.Result, error) {
	return q.exec(ctx, q.assignUserRoleByNameStmt, assignUserRoleByName, arg.UserID, arg.Name)
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :execresult
UPDATE refresh_tokens
SET
    used_at = NOW()
WHERE
    id = ?
    AND used_at IS NULL
    AND revoked_at IS NULL
`

// Atomically marks a refresh token as used in a single UPDATE.
// The WHERE used_at IS NULL guard means exactly one concurrent caller
// will get RowsAffected = 1; every other caller racing on the same token
// gets RowsAffected = 0, which the service layer treats as token reuse.
func (q *Queries) ConsumeRefreshToken(ctx context.Context, id string) (sql.Result, error) {
	return q.exec(ctx, q.consumeRefreshTokenStmt, consumeRefreshToken, id)
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO
    refresh_tokens (
        id,
        user_id,
        token_hash,
        token_family,
        expires_at,
        created_at
    )
VALUES (?, ?, ?, ?, ?, NOW())
`

type CreateRefreshTokenParams struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	TokenHash   string    `json:"token_hash"`
	TokenFamily string    `json:"token_family"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.exec(ctx, q.createRefreshTokenStmt, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.TokenFamily,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO
    users (
        id,
        email,
        password_hash,
        name,
        created_at,
        updated_at
    )
VALUES (?, ?, ?, ?, NOW(), NOW())
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.exec(ctx, q.createUserStmt, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT
    id,
    user_id,
    token_hash,
    token_family,
    expires_at,
    used_at,
    revoked_at,
    created_at
FROM refresh_tokens
WHERE
    token_hash = ?
LIMIT 1
`

// BUG FIX: removed `AND revoked_at IS NULL` — the previous filter made the
// token.RevokedAt.Valid checks in auth/service.go unreachable dead code.
// The application layer now receives the full record and returns the correct
// typed error (ErrTokenRevoked vs ErrTokenInvalid) for each case.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.queryRow(ctx, q.getRefreshTokenByHashStmt, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenFamily,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, email_verified_at, two_fa_enabled, created_at, updated_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerifiedAt,
		&i.TwoFaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailWithRoles = `-- name: GetUserByEmailWithRoles :many
SELECT
    u.id,
    u.email,
    u.password_hash,
    u.name,
    u.email_verified_at,
    u.two_fa_enabled,
    u.created_at,
    u.updated_at,
    r.id AS role_id,
    r.name AS role_name,
    r.description AS role_description
FROM
    users u
    LEFT JOIN user_roles ur ON ur.user_id = u.id
    LEFT JOIN roles r ON r.id = ur.role_id
WHERE
    u.email = ?
`

type GetUserByEmailWithRolesRow struct {
	ID              string         `json:"id"`
	Email           string         `json:"email"`
	PasswordHash    string         `json:"password_hash"`
	Name            string         `json:"name"`
	EmailVerifiedAt sql.NullTime   `json:"email_verified_at"`
	TwoFaEnabled    bool           `json:"two_fa_enabled"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	RoleID          sql.NullInt32  `json:"role_id"`
	RoleName        sql.NullString `json:"role_name"`
	RoleDescription sql.NullString `json:"role_description"`
}

func (q *Queries) GetUserByEmailWithRoles(ctx context.Context, email string) ([]GetUserByEmailWithRolesRow, error) {
	rows, err := q.query(ctx, q.getUserByEmailWithRolesStmt, getUserByEmailWithRoles, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserByEmailWithRolesRow{}
	for rows.Next() {
		var i GetUserByEmailWithRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.EmailVerifiedAt,
			&i.TwoFaEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleID,
			&i.RoleName,
			&i.RoleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, email_verified_at, two_fa_enabled, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerifiedAt,
		&i.TwoFaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIDWithRoles = `-- name: GetUserByIDWithRoles :many
SELECT
    u.id,
    u.email,
    u.password_hash,
    u.name,
    u.email_verified_at,
    u.two_fa_enabled,
    u.created_at,
    u.updated_at,
    r.id AS role_id,
    r.name AS role_name,
    r.description AS role_description
FROM
    users u
    LEFT JOIN user_roles ur ON ur.user_id = u.id
    LEFT JOIN roles r ON r.id = ur.role_id
WHERE
    u.id = ?
`

type GetUserByIDWithRolesRow struct {
	ID              string         `json:"id"`
	Email           string         `json:"email"`
	PasswordHash    string         `json:"password_hash"`
	Name            string         `json:"name"`
	EmailVerifiedAt sql.NullTime   `json:"email_verified_at"`
	TwoFaEnabled    bool           `json:"two_fa_enabled"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	RoleID          sql.NullInt32  `json:"role_id"`
	RoleName        sql.NullString `json:"role_name"`
	RoleDescription sql.NullString `json:"role_description"`
}

func (q *Queries) GetUserByIDWithRoles(ctx context.Context, id string) ([]GetUserByIDWithRolesRow, error) {
	rows, err := q.query(ctx, q.getUserByIDWithRolesStmt, getUserByIDWithRoles, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserByIDWithRolesRow{}
	for rows.Next() {
		var i GetUserByIDWithRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.EmailVerifiedAt,
			&i.TwoFaEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleID,
			&i.RoleName,
			&i.RoleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW() WHERE id = ?
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.revokeRefreshTokenStmt, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET
    revoked_at = NOW()
WHERE
    token_family = ?
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, tokenFamily string) error {
	_, err := q.exec(ctx, q.revokeRefreshTokenFamilyStmt, revokeRefreshTokenFamily, tokenFamily)
	return err
}
