// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.assignUserRoleByNameStmt, err = db.PrepareContext(ctx, assignUserRoleByName); err != nil {
		return nil, fmt.Errorf("error preparing query AssignUserRoleByName: %w", err)
	}
	if q.consumeRefreshTokenStmt, err = db.PrepareContext(ctx, consumeRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query ConsumeRefreshToken: %w", err)
	}
	if q.createRefreshTokenStmt, err = db.PrepareContext(ctx, createRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRefreshToken: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.getRefreshTokenByHashStmt, err = db.PrepareContext(ctx, getRefreshTokenByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetRefreshTokenByHash: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByEmailWithRolesStmt, err = db.PrepareContext(ctx, getUserByEmailWithRoles); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmailWithRoles: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByIDWithRolesStmt, err = db.PrepareContext(ctx, getUserByIDWithRoles); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByIDWithRoles: %w", err)
	}
	if q.revokeRefreshTokenStmt, err = db.PrepareContext(ctx, revokeRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeRefreshToken: %w", err)
	}
	if q.revokeRefreshTokenFamilyStmt, err = db.PrepareContext(ctx, revokeRefreshTokenFamily); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeRefreshTokenFamily: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.assignUserRoleByNameStmt != nil {
		if cerr := q.assignUserRoleByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing assignUserRoleByNameStmt: %w", cerr)
		}
	}
	if q.consumeRefreshTokenStmt != nil {
		if cerr := q.consumeRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing consumeRefreshTokenStmt: %w", cerr)
		}
	}
	if q.createRefreshTokenStmt != nil {
		if cerr := q.createRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRefreshTokenStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.getRefreshTokenByHashStmt != nil {
		if cerr := q.getRefreshTokenByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRefreshTokenByHashStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByEmailWithRolesStmt != nil {
		if cerr := q.getUserByEmailWithRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailWithRolesStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByIDWithRolesStmt != nil {
		if cerr := q.getUserByIDWithRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDWithRolesStmt: %w", cerr)
		}
	}
	if q.revokeRefreshTokenStmt != nil {
		if cerr := q.revokeRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeRefreshTokenStmt: %w", cerr)
		}
	}
	if q.revokeRefreshTokenFamilyStmt != nil {
		if cerr := q.revokeRefreshTokenFamilyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeRefreshTokenFamilyStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	assignUserRoleByNameStmt     *sql.Stmt
	consumeRefreshTokenStmt      *sql.Stmt
	createRefreshTokenStmt       *sql.Stmt
	createUserStmt               *sql.Stmt
	getRefreshTokenByHashStmt    *sql.Stmt
	getUserByEmailStmt           *sql.Stmt
	getUserByEmailWithRolesStmt  *sql.Stmt
	getUserByIDStmt              *sql.Stmt
	getUserByIDWithRolesStmt     *sql.Stmt
	revokeRefreshTokenStmt       *sql.Stmt
	revokeRefreshTokenFamilyStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		assignUserRoleByNameStmt:     q.assignUserRoleByNameStmt,
		consumeRefreshTokenStmt:      q.consumeRefreshTokenStmt,
		createRefreshTokenStmt:       q.createRefreshTokenStmt,
		createUserStmt:               q.createUserStmt,
		getRefreshTokenByHashStmt:    q.getRefreshTokenByHashStmt,
		getUserByEmailStmt:           q.getUserByEmailStmt,
		getUserByEmailWithRolesStmt:  q.getUserByEmailWithRolesStmt,
		getUserByIDStmt:              q.getUserByIDStmt,
		getUserByIDWithRolesStmt:     q.getUserByIDWithRolesStmt,
		revokeRefreshTokenStmt:       q.revokeRefreshTokenStmt,
		revokeRefreshTokenFamilyStmt: q.revokeRefreshTokenFamilyStmt,
	}
}
