// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	ID          string       `json:"id"`
	UserID      string       `json:"user_id"`
	TokenHash   string       `json:"token_hash"`
	TokenFamily string       `json:"token_family"`
	ExpiresAt   time.Time    `json:"expires_at"`
	UsedAt      sql.NullTime `json:"used_at"`
	RevokedAt   sql.NullTime `json:"revoked_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
