// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const consumeLinkingState = `-- name: ConsumeLinkingState :one
SELECT payload, expires_at
FROM oauth_linking_states
WHERE nonce = ?
FOR UPDATE
`

type ConsumeLinkingStateRow struct {
	Payload   []byte    `json:"payload"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Atomically reads and deletes a linking state row. The FOR UPDATE lock
// serialises concurrent requests on the same nonce; only the first caller
// gets a row — all others get sql.ErrNoRows (→ ErrInvalidLinkingToken).
// This query must be executed inside a transaction by the caller.
func (q *Queries) ConsumeLinkingState(ctx context.Context, nonce string) (ConsumeLinkingStateRow, error) {
	row := q.queryRow(ctx, q.consumeLinkingStateStmt, consumeLinkingState, nonce)
	var i ConsumeLinkingStateRow
	err := row.Scan(&i.Payload, &i.ExpiresAt)
	return i, err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :exec

INSERT INTO user_oauth_accounts (
    id,
    user_id,
    provider,
    provider_id,
    provider_email,
    provider_name,
    access_token_encrypted,
    refresh_token_encrypted,
    token_expires_at,
    enc_key_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOAuthAccountParams struct {
	ID                    string         `json:"id"`
	UserID                string         `json:"user_id"`
	Provider              string         `json:"provider"`
	ProviderID            string         `json:"provider_id"`
	ProviderEmail         string         `json:"provider_email"`
	ProviderName          string         `json:"provider_name"`
	AccessTokenEncrypted  sql.NullString `json:"access_token_encrypted"`
	RefreshTokenEncrypted sql.NullString `json:"refresh_token_encrypted"`
	TokenExpiresAt        sql.NullTime   `json:"token_expires_at"`
	EncKeyID              string         `json:"enc_key_id"`
}

// OAuth queries for user_oauth_accounts and oauth_linking_states.
//
// After any change to this file, regenerate the Go data-access layer with:
//
//	sqlc generate
//
// from the repository root (requires sqlc ≥ 1.25 and a running MySQL instance
// or the mysql8 engine in sqlc Cloud).
func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error {
	_, err := q.exec(ctx, q.createOAuthAccountStmt, createOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.ProviderEmail,
		arg.ProviderName,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
		arg.EncKeyID,
	)
	return err
}

const deleteLinkingState = `-- name: DeleteLinkingState :exec
DELETE FROM oauth_linking_states
WHERE nonce = ?
`

// Deletes the consumed nonce. Must be called in the same transaction as
// ConsumeLinkingState immediately after a successful SELECT … FOR UPDATE.
func (q *Queries) DeleteLinkingState(ctx context.Context, nonce string) error {
	_, err := q.exec(ctx, q.deleteLinkingStateStmt, deleteLinkingState, nonce)
	return err
}

const getOAuthAccountByProviderID = `-- name: GetOAuthAccountByProviderID :one
SELECT
    id,
    user_id,
    provider,
    provider_id,
    provider_email,
    provider_name,
    access_token_encrypted,
    refresh_token_encrypted,
    token_expires_at,
    enc_key_id,
    created_at,
    updated_at
FROM user_oauth_accounts
WHERE provider    = ?
  AND provider_id = ?
LIMIT 1
`

type GetOAuthAccountByProviderIDParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetOAuthAccountByProviderID(ctx context.Context, arg GetOAuthAccountByProviderIDParams) (UserOauthAccount, error) {
	row := q.queryRow(ctx, q.getOAuthAccountByProviderIDStmt, getOAuthAccountByProviderID, arg.Provider, arg.ProviderID)
	var i UserOauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderEmail,
		&i.ProviderName,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.EncKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountByUserIDAndProvider = `-- name: GetOAuthAccountByUserIDAndProvider :one
SELECT
    id,
    user_id,
    provider,
    provider_id,
    provider_email,
    provider_name,
    access_token_encrypted,
    refresh_token_encrypted,
    token_expires_at,
    enc_key_id,
    created_at,
    updated_at
FROM user_oauth_accounts
WHERE user_id  = ?
  AND provider = ?
LIMIT 1
`

type GetOAuthAccountByUserIDAndProviderParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetOAuthAccountByUserIDAndProvider(ctx context.Context, arg GetOAuthAccountByUserIDAndProviderParams) (UserOauthAccount, error) {
	row := q.queryRow(ctx, q.getOAuthAccountByUserIDAndProviderStmt, getOAuthAccountByUserIDAndProvider, arg.UserID, arg.Provider)
	var i UserOauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderEmail,
		&i.ProviderName,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.EncKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOneTimeCodeForUpdate = `-- name: GetOneTimeCodeForUpdate :one
SELECT
    id,
    user_id,
    code_hash,
    expires_at,
    used_at,
    created_at
FROM oauth_one_time_codes
WHERE code_hash = ?
FOR UPDATE
`

// Retrieves and row-locks the code record for the duration of the surrounding
// transaction. Must be called from within an explicit BEGIN transaction.
// Returns sql.ErrNoRows when no matching code exists, which the repository
// maps to ErrInvalidOneTimeCode (unknown / expired / already used are all
// collapsed into one error to prevent oracle attacks).
func (q *Queries) GetOneTimeCodeForUpdate(ctx context.Context, codeHash string) (OauthOneTimeCode, error) {
	row := q.queryRow(ctx, q.getOneTimeCodeForUpdateStmt, getOneTimeCodeForUpdate, codeHash)
	var i OauthOneTimeCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const linkOAuthAccountToUser = `-- name: LinkOAuthAccountToUser :exec
INSERT INTO user_oauth_accounts (
    id,
    user_id,
    provider,
    provider_id,
    provider_email,
    provider_name,
    access_token_encrypted,
    refresh_token_encrypted,
    token_expires_at,
    enc_key_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type LinkOAuthAccountToUserParams struct {
	ID                    string         `json:"id"`
	UserID                string         `json:"user_id"`
	Provider              string         `json:"provider"`
	ProviderID            string         `json:"provider_id"`
	ProviderEmail         string         `json:"provider_email"`
	ProviderName          string         `json:"provider_name"`
	AccessTokenEncrypted  sql.NullString `json:"access_token_encrypted"`
	RefreshTokenEncrypted sql.NullString `json:"refresh_token_encrypted"`
	TokenExpiresAt        sql.NullTime   `json:"token_expires_at"`
	EncKeyID              string         `json:"enc_key_id"`
}

// Called during the explicit linking flow when an authenticated user
// intentionally connects a provider identity to their existing local account.
func (q *Queries) LinkOAuthAccountToUser(ctx context.Context, arg LinkOAuthAccountToUserParams) error {
	_, err := q.exec(ctx, q.linkOAuthAccountToUserStmt, linkOAuthAccountToUser,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.ProviderEmail,
		arg.ProviderName,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
		arg.EncKeyID,
	)
	return err
}

const listOAuthAccountsByUserID = `-- name: ListOAuthAccountsByUserID :many
SELECT
    id,
    provider,
    provider_id,
    provider_email,
    provider_name,
    token_expires_at,
    enc_key_id,
    created_at,
    updated_at
FROM user_oauth_accounts
WHERE user_id = ?
ORDER BY provider
`

type ListOAuthAccountsByUserIDRow struct {
	ID             string       `json:"id"`
	Provider       string       `json:"provider"`
	ProviderID     string       `json:"provider_id"`
	ProviderEmail  string       `json:"provider_email"`
	ProviderName   string       `json:"provider_name"`
	TokenExpiresAt sql.NullTime `json:"token_expires_at"`
	EncKeyID       string       `json:"enc_key_id"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

func (q *Queries) ListOAuthAccountsByUserID(ctx context.Context, userID string) ([]ListOAuthAccountsByUserIDRow, error) {
	rows, err := q.query(ctx, q.listOAuthAccountsByUserIDStmt, listOAuthAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOAuthAccountsByUserIDRow{}
	for rows.Next() {
		var i ListOAuthAccountsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderID,
			&i.ProviderEmail,
			&i.ProviderName,
			&i.TokenExpiresAt,
			&i.EncKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOneTimeCodeUsed = `-- name: MarkOneTimeCodeUsed :execresult
UPDATE oauth_one_time_codes
SET    used_at   = NOW()
WHERE  code_hash = ?
AND    used_at   IS NULL
`

// Atomically stamps used_at on the locked row.
// The WHERE used_at IS NULL guard is belt-and-suspenders after the FOR UPDATE
// lock: exactly one concurrent caller gets RowsAffected = 1; any racing caller
// (possible on DBs without strict row-level locking) gets 0 and is rejected.
// Must be called inside the same transaction as GetOneTimeCodeForUpdate.
func (q *Queries) MarkOneTimeCodeUsed(ctx context.Context, codeHash string) (sql.Result, error) {
	return q.exec(ctx, q.markOneTimeCodeUsedStmt, markOneTimeCodeUsed, codeHash)
}

const purgeExpiredLinkingStates = `-- name: PurgeExpiredLinkingStates :exec
DELETE FROM oauth_linking_states
WHERE expires_at < NOW()
LIMIT 50
`

// Lazy cleanup of abandoned linking states (user closed the tab, etc.).
// Called opportunistically inside ConsumeLinkingState; also suitable for a
// scheduled maintenance job in high-traffic deployments.
func (q *Queries) PurgeExpiredLinkingStates(ctx context.Context) error {
	_, err := q.exec(ctx, q.purgeExpiredLinkingStatesStmt, purgeExpiredLinkingStates)
	return err
}

const purgeExpiredOneTimeCodes = `-- name: PurgeExpiredOneTimeCodes :exec
DELETE FROM oauth_one_time_codes
WHERE expires_at < NOW()
AND   used_at    IS NOT NULL
LIMIT 50
`

// Lazy cleanup of rows whose TTL has passed and have already been consumed.
// Called opportunistically inside ConsumeOneTimeCode (best-effort; errors ignored).
// For high-traffic deployments supplement with a scheduled job:
//
//	DELETE FROM oauth_one_time_codes
//	WHERE expires_at < NOW() AND used_at IS NOT NULL LIMIT 500;
func (q *Queries) PurgeExpiredOneTimeCodes(ctx context.Context) error {
	_, err := q.exec(ctx, q.purgeExpiredOneTimeCodesStmt, purgeExpiredOneTimeCodes)
	return err
}

const storeLinkingState = `-- name: StoreLinkingState :exec

INSERT INTO oauth_linking_states (nonce, payload, expires_at)
VALUES (?, ?, ?)
`

type StoreLinkingStateParams struct {
	Nonce     string    `json:"nonce"`
	Payload   []byte    `json:"payload"`
	ExpiresAt time.Time `json:"expires_at"`
}

// ── oauth_linking_states ───────────────────────────────────────────────────────
// Server-side storage for the email-collision linking flow.
// The nonce (HMAC-signed) travels to the client; the payload stays on the server.
// These queries replace the previous approach of embedding encrypted token blobs
// in the client-visible linking_token. Run `sqlc generate` after adding these.
// Persists a linking payload keyed by a 32-byte random nonce (hex-encoded).
// Called when an OAuth callback detects an email collision with an existing
// local account. expiresAt mirrors the 15-minute linkingTokenTTL.
func (q *Queries) StoreLinkingState(ctx context.Context, arg StoreLinkingStateParams) error {
	_, err := q.exec(ctx, q.storeLinkingStateStmt, storeLinkingState, arg.Nonce, arg.Payload, arg.ExpiresAt)
	return err
}

const storeOneTimeCode = `-- name: StoreOneTimeCode :exec

INSERT INTO oauth_one_time_codes (id, user_id, code_hash, expires_at)
VALUES (?, ?, ?, ?)
`

type StoreOneTimeCodeParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CodeHash  string    `json:"code_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

// oauth_one_time_codes queries — mobile OAuth exchange flow.
//
// Table added in migration 0008. Run `sqlc generate` after editing this file.
//
// Naming conventions mirror oauth.sql patterns:
//
//	:exec        — INSERT / DELETE with no return value
//	:execresult  — UPDATE where RowsAffected is checked (single-use guard)
//	:one         — SELECT returning a single row (used inside a transaction)
//
// Query naming rationale:
//
//	StoreOneTimeCode        — symmetric with StoreLinkingState in oauth.sql
//	GetOneTimeCodeForUpdate — explicit "ForUpdate" suffix signals the caller
//	                          MUST wrap this in a transaction; see ConsumeOneTimeCode
//	MarkOneTimeCodeUsed     — mirrors ConsumeEmailToken / ConsumeRefreshToken patterns
//	PurgeExpiredOneTimeCodes— mirrors PurgeExpiredLinkingStates in oauth.sql
//
// Persists the SHA-256 hex hash of the 64-char random plaintext code.
// The plaintext is never written to any store — only SHA-256(plaintext) is here.
// Called immediately after code generation in service.IssueOneTimeCode.
func (q *Queries) StoreOneTimeCode(ctx context.Context, arg StoreOneTimeCodeParams) error {
	_, err := q.exec(ctx, q.storeOneTimeCodeStmt, storeOneTimeCode,
		arg.ID,
		arg.UserID,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const unlinkOAuthAccount = `-- name: UnlinkOAuthAccount :exec
DELETE FROM user_oauth_accounts
WHERE user_id  = ?
  AND provider = ?
`

type UnlinkOAuthAccountParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) UnlinkOAuthAccount(ctx context.Context, arg UnlinkOAuthAccountParams) error {
	_, err := q.exec(ctx, q.unlinkOAuthAccountStmt, unlinkOAuthAccount, arg.UserID, arg.Provider)
	return err
}

const updateOAuthTokens = `-- name: UpdateOAuthTokens :exec
UPDATE user_oauth_accounts
SET
    access_token_encrypted  = ?,
    refresh_token_encrypted = ?,
    token_expires_at        = ?,
    enc_key_id              = ?,
    updated_at              = NOW()
WHERE provider    = ?
  AND provider_id = ?
`

type UpdateOAuthTokensParams struct {
	AccessTokenEncrypted  sql.NullString `json:"access_token_encrypted"`
	RefreshTokenEncrypted sql.NullString `json:"refresh_token_encrypted"`
	TokenExpiresAt        sql.NullTime   `json:"token_expires_at"`
	EncKeyID              string         `json:"enc_key_id"`
	Provider              string         `json:"provider"`
	ProviderID            string         `json:"provider_id"`
}

func (q *Queries) UpdateOAuthTokens(ctx context.Context, arg UpdateOAuthTokensParams) error {
	_, err := q.exec(ctx, q.updateOAuthTokensStmt, updateOAuthTokens,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
		arg.EncKeyID,
		arg.Provider,
		arg.ProviderID,
	)
	return err
}
