// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: totp.sql

package db

import (
	"context"
	"database/sql"
)

const disableUserTOTP = `-- name: DisableUserTOTP :exec
UPDATE users
SET mfa_method               = 'email',
    two_fa_enabled           = 0,
    totp_secret_encrypted    = NULL,
    totp_enabled_at          = NULL
WHERE id = ?
`

// Reverts the user to email OTP and clears the stored secret.
// two_fa_enabled is set to 0 so the Login gate (which checks two_fa_enabled)
// no longer routes this user through the MFA challenge path. Without this,
// mfa_method and two_fa_enabled would desync: mfa_method='email' but
// two_fa_enabled=1 causes Login to issue an MFA challenge, InitiateChallenge
// dispatches to the email-OTP branch, but no OTP token was ever created for
// this login attempt — producing an infinite challenge loop with no valid
// redemption path until the challenge token expires (5 minutes).
func (q *Queries) DisableUserTOTP(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.disableUserTOTPStmt, disableUserTOTP, id)
	return err
}

const enableUserTOTP = `-- name: EnableUserTOTP :exec
UPDATE users
SET mfa_method       = 'totp',
    two_fa_enabled   = 1,
    totp_enabled_at  = UTC_TIMESTAMP()
WHERE id = ?
`

// Activates TOTP after the user confirms possession of the secret.
func (q *Queries) EnableUserTOTP(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.enableUserTOTPStmt, enableUserTOTP, id)
	return err
}

const getUserMFAMethod = `-- name: GetUserMFAMethod :one
SELECT mfa_method
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserMFAMethod(ctx context.Context, id string) (UsersMfaMethod, error) {
	row := q.queryRow(ctx, q.getUserMFAMethodStmt, getUserMFAMethod, id)
	var mfa_method UsersMfaMethod
	err := row.Scan(&mfa_method)
	return mfa_method, err
}

const getUserTOTPSecretEncrypted = `-- name: GetUserTOTPSecretEncrypted :one
SELECT totp_secret_encrypted
FROM users
WHERE id = ?
LIMIT 1
`

// Returns NULL when the column is NULL (TOTP not yet set up).
func (q *Queries) GetUserTOTPSecretEncrypted(ctx context.Context, id string) (sql.NullString, error) {
	row := q.queryRow(ctx, q.getUserTOTPSecretEncryptedStmt, getUserTOTPSecretEncrypted, id)
	var totp_secret_encrypted sql.NullString
	err := row.Scan(&totp_secret_encrypted)
	return totp_secret_encrypted, err
}

const setUserTOTPSecret = `-- name: SetUserTOTPSecret :exec
UPDATE users
SET totp_secret_encrypted = ?
WHERE id = ?
`

type SetUserTOTPSecretParams struct {
	TotpSecretEncrypted sql.NullString `json:"totp_secret_encrypted"`
	ID                  string         `json:"id"`
}

// Stores the encrypted TOTP secret (pending; not yet active).
func (q *Queries) SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error {
	_, err := q.exec(ctx, q.setUserTOTPSecretStmt, setUserTOTPSecret, arg.TotpSecretEncrypted, arg.ID)
	return err
}
